spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-imooc-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-imooc-test
