spring:
  profiles:
    active:
      -dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.imooc.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: 123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
    username: root
eureka:
    client:
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/
    instance:
      instance-id: microservicecloud-dept8001
      prefer-ip-address: true #显示ip地址
info:
  app.name: com.imooc-microservicecloud
  company.name: www.com.imooc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.imooc.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: test
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb02?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: 123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
    username: root
eureka:
    client:
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/
    instance:
      instance-id: microservicecloud-dept8001
      prefer-ip-address: true #显示ip地址
info:
  app.name: com.imooc-microservicecloud
  company.name: www.com.imooc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
